### ISSUE TITLE
Error when running Training on lazy mode

### ISSUE THREAD

**Issue by wsalmen2** [ml-struct-bio/drgnai#11]
Hello,
I am currently encountering issues with running the drgnai train job on version 0.3.1-beta

A quick summary, I have already successfully ran cryodrgn training with a downsampled particle stack set to 256 pix. ie. particles_256.mrcs. Using this particle stack, I ran the command:

drgnai setup . --particles /particlepath/particles_256.mrcs --ctf /ctfpath/ctf.pkl --capture-setup spa --reconstruction-type het --conf-estimation autodecoder --pose-estimation abinit --cfgs 'lazy=True'

After drgnai setup, I ran drgnai train workdir  and receive the below error. Does drgnai use considerably more memory than cryodrgn train? Any advice on how to resolve this would be greatly appreciated.

-Wil

(INFO) (reconstruct.py) (02-Oct-24 12:32:09) --- Training Starts Now ---
(INFO) (reconstruct.py) (02-Oct-24 12:32:09) Will pretrain on 10000 particles
(INFO) (reconstruct.py) (02-Oct-24 12:32:09) Will make a full summary at the end of this epoch
Traceback (most recent call last):
  File "/Users/salmen/.local/bin/drgnai", line 8, in <module>
    sys.exit(run_cryodrgn_ai())
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgnai/command_line.py", line 168, in run_cryodrgn_ai
    args.func(args)
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgnai/command_line.py", line 322, in train_experiment
    trainer.train()
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgnai/reconstruct.py", line 754, in train
    self.train_step(in_dict, end_time=end_time)
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgnai/reconstruct.py", line 851, in train_step
    latent_variables_dict, y_pred, y_gt_processed = self.forward_pass(
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgnai/reconstruct.py", line 1021, in forward_pass
    out_dict = self.model(in_dict)
  File "/Users/salmen/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/salmen/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/salmen/.local/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/Users/salmen/.local/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 201, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/Users/salmen/.local/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 109, in parallel_apply
    output.reraise()
  File "/Users/salmen/.local/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
torch.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.

**Comment by michal-g** [comment]
Hey Wil, your best bet for making the memory usage manageable here is reducing the `batch_size_sgd` configuration parameter using `--cfgs` (or just add another line to your `configs.yaml`). The default value is 256 but you should try something like 32 or 64 (or even 8) and see if that resolves the issue!

-Mike

**Comment by wsalmen2** [comment]
Thank you! It worked after switching the batch size sgd to 32.
